apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pregnant-constrictor-go-prod
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/pregnant-constrictor-go/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/pregnant-constrictor-go-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-e2e-ci-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
