apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pregnant-constrictor-go 
  janus-idp.io/tekton: pregnant-constrictor-go
  backstage.io/kubernetes-id: pregnant-constrictor-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: pregnant-constrictor-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  