apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pregnant-constrictor-go-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pregnant-constrictor-go-gitops